/* data.js — NSW spots, tide reference ports, BOM radars, species.
   All static. Nothing here needs the network. */
(function (global) {
  'use strict';

  /* ---------------- BOM tide standard ports ---------------------------- */
  /* aac = BOM Australian Area Code used by the tide product.
     msl = metres to add to a mean-sea-level height to land on the chart
     datum BOM tide tables use (MHL station datum analysis, 1995-2014). */
  var PORTS = {
    yamba:      { name: 'Yamba',              aac: 'NSW_TP008', lat: -29.43, lon: 153.36, msl: 0.945 },
    newcastle:  { name: 'Newcastle',          aac: 'NSW_TP004', lat: -32.92, lon: 151.79, msl: 0.93 },
    sydney:     { name: 'Sydney (Fort Denison)', aac: 'NSW_TP007', lat: -33.85, lon: 151.23, msl: 0.965 },
    botany:     { name: 'Botany Bay',         aac: 'NSW_TP001', lat: -33.98, lon: 151.21, msl: 0.93 },
    portkembla: { name: 'Port Kembla',        aac: 'NSW_TP006', lat: -34.47, lon: 150.91, msl: 0.93 },
    eden:       { name: 'Eden',               aac: 'NSW_TP002', lat: -37.07, lon: 149.90, msl: 0.844 }
  };

  /* ---------------- BOM radars ----------------------------------------- */
  var RADARS = {
    IDR283: { name: 'Grafton',            lat: -29.62, lon: 152.97, base: 'IDR28' },
    IDR043: { name: 'Newcastle',          lat: -32.73, lon: 152.03, base: 'IDR04' },
    IDR713: { name: 'Sydney (Terrey Hills)', lat: -33.70, lon: 151.21, base: 'IDR71' },
    IDR033: { name: 'Wollongong (Appin)', lat: -34.26, lon: 150.87, base: 'IDR03' },
    IDR403: { name: 'Canberra (Captains Flat)', lat: -35.66, lon: 149.51, base: 'IDR40' },
    IDR553: { name: 'Wagga Wagga',        lat: -35.17, lon: 147.47, base: 'IDR55' },
    IDR533: { name: 'Moree',              lat: -29.50, lon: 149.85, base: 'IDR53' },
    IDR693: { name: 'Namoi',              lat: -31.02, lon: 150.19, base: 'IDR69' },
    IDR963: { name: 'Yeoval',             lat: -32.74, lon: 148.70, base: 'IDR96' },
    IDR943: { name: 'Hillston',           lat: -33.55, lon: 145.52, base: 'IDR94' },
    IDR933: { name: 'Brewarrina',         lat: -29.96, lon: 146.81, base: 'IDR93' },
    IDR663: { name: 'Brisbane (Mt Stapylton)', lat: -27.72, lon: 153.24, base: 'IDR66' },
    IDR683: { name: 'Bairnsdale',         lat: -37.89, lon: 147.58, base: 'IDR68' }
  };

  /* ---------------- BOM coastal waters districts ------------------------ */
  var DISTRICTS = {
    byron:     'Byron Coast',
    coffs:     'Coffs Coast',
    macquarie: 'Macquarie Coast',
    hunter:    'Hunter Coast',
    sydney:    'Sydney Coast',
    illawarra: 'Illawarra Coast',
    batemans:  'Batemans Coast',
    eden:      'Eden Coast'
  };

  /* ---------------- Spots ----------------------------------------------
     [ name, region, lat, lon, seaLat, seaLon, port, hwOffMin, lwOffMin,
       radar, district, kinds, note, faces ]
     kinds: e estuary  b beach  r rock  o offshore  f freshwater
     Offsets are minutes to ADD to the reference port's tide time. Open-coast
     entrances are 0; upriver figures come from the NSW tide tables.
     A note beginning "!" flags a spot where tide HEIGHTS are unreliable
     (damped lake or far upriver) even though the times are usable.        */
  var SPOT_ROWS = [
    // ---- Far North Coast
    ['Tweed Heads / Tweed River', 'Far North Coast', -28.171, 153.545, -28.17, 153.94, 'yamba', 30, 60, 'IDR663', 'byron', 'ebro', '', 90],
    ['Kingscliff', 'Far North Coast', -28.256, 153.581, -28.26, 153.96, 'yamba', 0, 0, 'IDR663', 'byron', 'bro', '', 80],
    ['Brunswick Heads', 'Far North Coast', -28.540, 153.552, -28.54, 153.95, 'yamba', 6, 6, 'IDR663', 'byron', 'ebro', '', 80],
    ['Byron Bay', 'Far North Coast', -28.643, 153.612, -28.64, 154.01, 'yamba', 0, 0, 'IDR663', 'byron', 'bro', '', 70],
    ['Ballina / Richmond River', 'Far North Coast', -28.868, 153.586, -28.87, 153.97, 'yamba', 15, 15, 'IDR283', 'byron', 'ebro', '', 90],
    ['Evans Head', 'Far North Coast', -29.115, 153.432, -29.12, 153.83, 'yamba', 10, 10, 'IDR283', 'byron', 'ebro', '', 90],
    ['Yamba / Clarence River', 'Far North Coast', -29.437, 153.362, -29.44, 153.76, 'yamba', 0, 0, 'IDR283', 'coffs', 'ebro', '', 80],
    ['Iluka', 'Far North Coast', -29.410, 153.354, -29.41, 153.76, 'yamba', 0, 0, 'IDR283', 'coffs', 'ebr', '', 70],
    ['Maclean (Clarence)', 'Far North Coast', -29.457, 153.198, null, null, 'yamba', 135, 145, 'IDR283', 'coffs', 'e', '!Well upriver — heights are much smaller than at the entrance.', null],
    ['Grafton (Clarence)', 'Far North Coast', -29.690, 152.933, null, null, 'yamba', 250, 270, 'IDR283', 'coffs', 'ef', '!Far upriver — treat heights as indicative only.', null],
    // ---- North / Mid North Coast
    ['Wooli', 'North Coast', -29.867, 153.267, -29.87, 153.66, 'yamba', 10, 10, 'IDR283', 'coffs', 'ebro', '', 90],
    ['Coffs Harbour', 'North Coast', -30.301, 153.144, -30.30, 153.54, 'yamba', 0, 0, 'IDR283', 'coffs', 'bro', '', 100],
    ['Sawtell', 'North Coast', -30.373, 153.104, -30.37, 153.50, 'yamba', 0, 0, 'IDR283', 'coffs', 'bro', '', 90],
    ['Nambucca Heads', 'Mid North Coast', -30.643, 153.006, -30.64, 153.40, 'newcastle', 10, 10, 'IDR043', 'coffs', 'ebro', '', 80],
    ['South West Rocks', 'Mid North Coast', -30.885, 153.041, -30.89, 153.44, 'newcastle', 23, 23, 'IDR043', 'macquarie', 'ebro', '', 40],
    ['Port Macquarie', 'Mid North Coast', -31.431, 152.911, -31.44, 153.31, 'newcastle', 20, 20, 'IDR043', 'macquarie', 'ebro', '', 80],
    ['Camden Haven / Laurieton', 'Mid North Coast', -31.646, 152.797, -31.66, 153.17, 'newcastle', 30, 60, 'IDR043', 'macquarie', 'ebro', '', 90],
    ['Crowdy Head', 'Mid North Coast', -31.837, 152.752, -31.84, 153.15, 'newcastle', 5, 5, 'IDR043', 'macquarie', 'bro', '', 70],
    ['Harrington / Manning River', 'Mid North Coast', -31.871, 152.688, -31.87, 153.10, 'newcastle', 15, 20, 'IDR043', 'macquarie', 'ebro', '', 80],
    ['Forster / Tuncurry', 'Mid North Coast', -32.180, 152.516, -32.19, 152.91, 'newcastle', 5, 5, 'IDR043', 'macquarie', 'ebro', '', 90],
    ['Wallis Lake', 'Mid North Coast', -32.253, 152.483, null, null, 'newcastle', 90, 120, 'IDR043', 'macquarie', 'e', '!Big lake system — the tide is heavily damped, heights are far smaller inside.', null],
    ['Seal Rocks', 'Mid North Coast', -32.442, 152.535, -32.45, 152.93, 'newcastle', 0, 0, 'IDR043', 'hunter', 'bro', '', 110],
    // ---- Hunter / Central Coast
    ['Port Stephens (Nelson Bay)', 'Hunter', -32.716, 152.148, -32.72, 152.58, 'newcastle', 30, 15, 'IDR043', 'hunter', 'ebro', '', 60],
    ['Tea Gardens / Myall River', 'Hunter', -32.664, 152.156, null, null, 'newcastle', 90, 90, 'IDR043', 'hunter', 'e', '', null],
    ['Stockton Beach', 'Hunter', -32.880, 151.800, -32.88, 152.20, 'newcastle', 0, 0, 'IDR043', 'hunter', 'bro', '', 110],
    ['Newcastle Harbour / Hunter River', 'Hunter', -32.925, 151.790, -32.93, 152.19, 'newcastle', 0, 0, 'IDR043', 'hunter', 'ebro', '', 90],
    ['Swansea Channel', 'Hunter', -33.088, 151.646, -33.09, 152.04, 'newcastle', 20, 30, 'IDR043', 'hunter', 'eb', '', 100],
    ['Lake Macquarie', 'Hunter', -33.060, 151.590, null, null, 'newcastle', 120, 160, 'IDR043', 'hunter', 'e', '!Australia’s largest coastal lake — tide range inside is only a fraction of the ocean.', null],
    ['Norah Head', 'Central Coast', -33.283, 151.578, -33.28, 151.98, 'sydney', 0, 0, 'IDR713', 'hunter', 'bro', '', 90],
    ['The Entrance / Tuggerah Lakes', 'Central Coast', -33.345, 151.500, -33.35, 151.90, 'sydney', 30, 60, 'IDR713', 'hunter', 'eb', '!Lake side is damped; the channel runs hard.', 100],
    ['Terrigal / Avoca', 'Central Coast', -33.447, 151.446, -33.45, 151.85, 'sydney', 0, 0, 'IDR713', 'sydney', 'bro', '', 110],
    ['Brisbane Water (Gosford)', 'Central Coast', -33.470, 151.330, null, null, 'sydney', 60, 75, 'IDR713', 'sydney', 'e', '', null],
    ['Hawkesbury River (Brooklyn)', 'Central Coast', -33.545, 151.207, null, null, 'sydney', 60, 60, 'IDR713', 'sydney', 'ef', '', null],
    ['Wisemans Ferry (Hawkesbury)', 'Central Coast', -33.383, 150.980, null, null, 'sydney', 145, 155, 'IDR713', 'sydney', 'ef', '!Far upriver — heights indicative only.', null],
    // ---- Sydney
    ['Pittwater / Broken Bay', 'Sydney', -33.600, 151.300, -33.58, 151.69, 'sydney', 8, 8, 'IDR713', 'sydney', 'ebro', '', 20],
    ['Palm Beach', 'Sydney', -33.598, 151.325, -33.60, 151.71, 'sydney', 5, 5, 'IDR713', 'sydney', 'bro', '', 90],
    ['Narrabeen / Long Reef', 'Sydney', -33.730, 151.300, -33.73, 151.69, 'sydney', 3, 3, 'IDR713', 'sydney', 'ebro', '', 100],
    ['Middle Harbour / The Spit', 'Sydney', -33.803, 151.246, -33.83, 151.66, 'sydney', 0, 0, 'IDR713', 'sydney', 'e', '', null],
    ['Sydney Harbour', 'Sydney', -33.855, 151.230, -33.84, 151.64, 'sydney', 0, 0, 'IDR713', 'sydney', 'ebro', '', 90],
    ['Parramatta River', 'Sydney', -33.840, 151.070, null, null, 'sydney', 14, 14, 'IDR713', 'sydney', 'e', '', null],
    ['Maroubra / Malabar', 'Sydney', -33.950, 151.260, -33.95, 151.65, 'sydney', 0, 0, 'IDR713', 'sydney', 'bro', '', 110],
    ['Botany Bay', 'Sydney', -33.980, 151.190, -34.01, 151.60, 'botany', 0, 0, 'IDR713', 'sydney', 'ebro', '', 90],
    ['Georges River', 'Sydney', -33.980, 151.070, null, null, 'botany', 30, 40, 'IDR713', 'sydney', 'e', '', null],
    ['Cronulla / Bate Bay', 'Sydney', -34.055, 151.155, -34.06, 151.55, 'botany', 0, 0, 'IDR713', 'sydney', 'bro', '', 120],
    ['Port Hacking', 'Sydney', -34.075, 151.130, -34.09, 151.54, 'botany', 5, 5, 'IDR713', 'sydney', 'ebro', '', 120],
    // ---- Illawarra
    ['Stanwell Park / Coalcliff', 'Illawarra', -34.230, 150.990, -34.23, 151.38, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'bro', '', 100],
    ['Wollongong', 'Illawarra', -34.424, 150.899, -34.42, 151.29, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'bro', '', 100],
    ['Port Kembla', 'Illawarra', -34.470, 150.910, -34.48, 151.30, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'ebro', '', 110],
    ['Lake Illawarra', 'Illawarra', -34.540, 150.850, null, null, 'portkembla', 75, 110, 'IDR033', 'illawarra', 'e', '!Damped lake — heights inside are much smaller.', null],
    ['Shellharbour / Bass Point', 'Illawarra', -34.580, 150.870, -34.58, 151.26, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'bro', '', 120],
    ['Kiama', 'Illawarra', -34.672, 150.855, -34.67, 151.24, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'bro', '', 110],
    ['Gerroa / Seven Mile Beach', 'Illawarra', -34.760, 150.810, -34.76, 151.20, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'bro', '', 110],
    // ---- South Coast (Shoalhaven / Jervis Bay)
    ['Shoalhaven Heads', 'South Coast', -34.851, 150.745, -34.85, 151.14, 'portkembla', 65, 70, 'IDR033', 'illawarra', 'ebr', '', 100],
    ['Crookhaven Heads / Culburra', 'South Coast', -34.905, 150.752, -34.91, 151.15, 'portkembla', 16, 16, 'IDR033', 'batemans', 'ebro', '', 100],
    ['Greenwell Point', 'South Coast', -34.905, 150.720, null, null, 'portkembla', 45, 45, 'IDR033', 'batemans', 'e', '', null],
    ['Nowra (Shoalhaven River)', 'South Coast', -34.876, 150.600, null, null, 'portkembla', 125, 140, 'IDR033', 'batemans', 'ef', '!Well upriver — heights indicative only.', null],
    ['Currarong', 'South Coast', -35.011, 150.827, -35.01, 151.23, 'portkembla', 5, 5, 'IDR033', 'batemans', 'bro', '', 40],
    ['Callala Bay', 'South Coast', -35.001, 150.706, -35.05, 151.14, 'portkembla', 8, 8, 'IDR033', 'batemans', 'ebro', 'Jervis Bay Marine Park — check the zoning before you fish.', 130],
    ['Huskisson (Jervis Bay)', 'South Coast', -35.041, 150.669, -35.08, 151.14, 'portkembla', 8, 8, 'IDR033', 'batemans', 'ebro', 'Jervis Bay Marine Park — check the zoning before you fish.', 80],
    ['Vincentia / Plantation Point', 'South Coast', -35.077, 150.677, -35.10, 151.14, 'portkembla', 8, 8, 'IDR033', 'batemans', 'ebro', 'Jervis Bay Marine Park — check the zoning before you fish.', 40],
    ['Sussex Inlet', 'South Coast', -35.157, 150.586, -35.17, 151.02, 'portkembla', 45, 75, 'IDR033', 'batemans', 'eb', '!St Georges Basin behind the inlet is heavily damped.', 110],
    ['Ulladulla / Mollymook', 'South Coast', -35.355, 150.474, -35.36, 150.88, 'portkembla', 0, 0, 'IDR033', 'batemans', 'ebro', '', 100],
    ['Burrill Lake', 'South Coast', -35.390, 150.450, -35.40, 150.88, 'portkembla', 55, 80, 'IDR033', 'batemans', 'eb', '!Damped lake — the beach side at Dolphin Point is open surf.', 100],
    ['Batemans Bay / Clyde River', 'South Coast', -35.708, 150.180, -35.72, 150.60, 'eden', 15, 15, 'IDR403', 'batemans', 'ebro', '', 80],
    ['Moruya River', 'South Coast', -35.910, 150.150, -35.92, 150.56, 'eden', 20, 25, 'IDR403', 'batemans', 'ebro', '', 100],
    ['Narooma / Wagonga Inlet', 'Far South Coast', -36.213, 150.135, -36.22, 150.56, 'eden', 45, 30, 'IDR403', 'batemans', 'ebro', '', 100],
    ['Bermagui', 'Far South Coast', -36.424, 150.072, -36.43, 150.50, 'eden', 8, 8, 'IDR403', 'eden', 'ebro', '', 90],
    ['Tathra', 'Far South Coast', -36.733, 149.983, -36.74, 150.41, 'eden', 5, 5, 'IDR403', 'eden', 'bro', '', 100],
    ['Merimbula', 'Far South Coast', -36.892, 149.912, -36.90, 150.34, 'eden', 40, 60, 'IDR683', 'eden', 'ebro', '', 130],
    ['Pambula River', 'Far South Coast', -36.945, 149.900, -36.95, 150.33, 'eden', 40, 55, 'IDR683', 'eden', 'eb', '', 110],
    ['Eden / Twofold Bay', 'Far South Coast', -37.065, 149.902, -37.08, 150.33, 'eden', 8, 8, 'IDR683', 'eden', 'ebro', '', 90],
    // ---- Inland / freshwater
    ['Lake Jindabyne', 'Inland', -36.412, 148.622, null, null, null, 0, 0, 'IDR403', null, 'f', '', null],
    ['Lake Eucumbene', 'Inland', -36.130, 148.630, null, null, null, 0, 0, 'IDR403', null, 'f', '', null],
    ['Thredbo River', 'Inland', -36.500, 148.330, null, null, null, 0, 0, 'IDR403', null, 'f', '', null],
    ['Tantangara / Upper Murrumbidgee', 'Inland', -35.800, 148.650, null, null, null, 0, 0, 'IDR403', null, 'f', '', null],
    ['Burrinjuck Dam', 'Inland', -35.000, 148.600, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Blowering Dam', 'Inland', -35.400, 148.250, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Wyangala Dam', 'Inland', -33.960, 148.960, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Burrendong Dam', 'Inland', -32.670, 149.100, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Copeton Dam', 'Inland', -29.900, 150.940, null, null, null, 0, 0, 'IDR533', null, 'f', '', null],
    ['Keepit Dam', 'Inland', -30.880, 150.500, null, null, null, 0, 0, 'IDR693', null, 'f', '', null],
    ['Glenbawn Dam', 'Inland', -32.100, 151.030, null, null, null, 0, 0, 'IDR043', null, 'f', '', null],
    ['Lake Windamere', 'Inland', -32.720, 149.850, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Murray River (Albury)', 'Inland', -36.070, 146.920, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Murrumbidgee (Wagga)', 'Inland', -35.110, 147.370, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Darling River (Bourke)', 'Inland', -30.090, 145.940, null, null, null, 0, 0, 'IDR933', null, 'f', '', null],
    ['Nepean River (Penrith)', 'Inland', -33.750, 150.680, null, null, null, 0, 0, 'IDR713', null, 'f', '', null],
    // ---- added Sept 2026: gaps along the coast and inland
    ['Pottsville', 'Far North Coast', -28.386, 153.567, -28.39, 153.95, 'yamba', 0, 0, 'IDR663', 'byron', 'b', '', 80],
    ['Lennox Head', 'Far North Coast', -28.793, 153.594, -28.79, 153.98, 'yamba', 0, 0, 'IDR283', 'byron', 'br', '', 80],
    ['Woodburn (Richmond River)', 'Far North Coast', -29.072, 153.343, null, null, 'yamba', 90, 120, 'IDR283', 'byron', 'e', '!Well up the river — the tide runs over an hour behind Ballina and the range is small.', null],
    ['Brooms Head', 'Far North Coast', -29.608, 153.336, -29.61, 153.72, 'yamba', 0, 0, 'IDR283', 'byron', 'br', '', 90],
    ['Minnie Water / Sandon River', 'Far North Coast', -29.776, 153.297, -29.78, 153.68, 'yamba', 10, 10, 'IDR283', 'byron', 'ebr', '', 90],
    ['Red Rock', 'North Coast', -29.982, 153.227, -29.98, 153.62, 'yamba', 5, 5, 'IDR283', 'coffs', 'eb', '', 80],
    ['Woolgoolga / Arrawarra', 'North Coast', -30.111, 153.201, -30.11, 153.60, 'yamba', 0, 0, 'IDR283', 'coffs', 'bro', '', 80],
    ['Urunga (Bellinger River)', 'North Coast', -30.497, 153.014, -30.50, 153.40, 'yamba', 20, 35, 'IDR283', 'coffs', 'eb', '', 90],
    ['Scotts Head', 'North Coast', -30.748, 152.997, -30.75, 153.38, 'yamba', 0, 0, 'IDR283', 'coffs', 'br', '', 80],
    ['Hat Head', 'Mid North Coast', -31.055, 153.049, -31.06, 153.44, 'newcastle', 5, 5, 'IDR043', 'macquarie', 'ebr', '', 80],
    ['Crescent Head', 'Mid North Coast', -31.190, 152.980, -31.19, 153.37, 'newcastle', 0, 0, 'IDR043', 'macquarie', 'bro', '', 90],
    ['Lake Cathie / Bonny Hills', 'Mid North Coast', -31.551, 152.856, -31.55, 153.25, 'newcastle', 20, 30, 'IDR043', 'macquarie', 'eb', '!The lake only runs when the entrance is open.', 90],
    ['Old Bar / Wallabi Point', 'Mid North Coast', -31.965, 152.594, -31.97, 152.99, 'newcastle', 5, 5, 'IDR043', 'macquarie', 'ebr', '', 90],
    ['Hallidays Point / Blackhead', 'Mid North Coast', -32.070, 152.545, -32.07, 152.94, 'newcastle', 0, 0, 'IDR043', 'macquarie', 'br', '', 100],
    ['Pacific Palms / Smiths Lake', 'Mid North Coast', -32.360, 152.520, -32.36, 152.92, 'newcastle', 10, 10, 'IDR043', 'macquarie', 'ebr', '', 100],
    ['Myall Lakes (Bulahdelah)', 'Hunter', -32.470, 152.270, null, null, 'newcastle', 240, 300, 'IDR043', 'hunter', 'e', '!Barely tidal — wind sets the water level here, not the moon.', null],
    ['Hawks Nest / Bennetts Beach', 'Hunter', -32.667, 152.183, -32.67, 152.58, 'newcastle', 10, 10, 'IDR043', 'hunter', 'ebr', '', 90],
    ['Anna Bay / Birubi', 'Hunter', -32.784, 152.083, -32.79, 152.48, 'newcastle', 0, 0, 'IDR043', 'hunter', 'br', '', 150],
    ['Catherine Hill Bay', 'Hunter', -33.164, 151.630, -33.16, 152.03, 'newcastle', 0, 0, 'IDR043', 'hunter', 'br', '', 100],
    ['Budgewoi / Toukley', 'Central Coast', -33.230, 151.560, -33.23, 151.96, 'sydney', 90, 120, 'IDR713', 'hunter', 'eb', '!Lake side is barely tidal.', 90],
    ['Ettalong / Umina', 'Central Coast', -33.514, 151.336, -33.53, 151.74, 'sydney', 15, 20, 'IDR713', 'sydney', 'eb', '', 150],
    ['Patonga', 'Central Coast', -33.548, 151.269, -33.53, 151.74, 'sydney', 20, 25, 'IDR713', 'sydney', 'eb', '', 120],
    ['Manly / North Head', 'Sydney', -33.799, 151.290, -33.80, 151.69, 'sydney', 0, 0, 'IDR713', 'sydney', 'bro', '', 90],
    ['Bondi / Bronte / Clovelly', 'Sydney', -33.897, 151.275, -33.90, 151.68, 'sydney', 0, 0, 'IDR713', 'sydney', 'br', '', 100],
    ['La Perouse / Kurnell', 'Sydney', -33.990, 151.230, -34.00, 151.63, 'botany', 0, 0, 'IDR713', 'sydney', 'ebro', '', 110],
    ['Windang / Lake Illawarra entrance', 'Illawarra', -34.531, 150.871, -34.53, 151.26, 'portkembla', 10, 15, 'IDR033', 'illawarra', 'eb', '', 100],
    ['Minnamurra River', 'Illawarra', -34.627, 150.855, -34.63, 151.25, 'portkembla', 10, 15, 'IDR033', 'illawarra', 'eb', '', 100],
    ['Gerringong / Werri Beach', 'Illawarra', -34.740, 150.836, -34.74, 151.23, 'portkembla', 0, 0, 'IDR033', 'illawarra', 'bro', '', 110],
    ['Lake Conjola', 'South Coast', -35.268, 150.502, -35.27, 150.90, 'portkembla', 60, 90, 'IDR033', 'batemans', 'eb', '!Lake tide depends on the entrance being open.', 100],
    ['Bendalong / Manyana', 'South Coast', -35.246, 150.535, -35.25, 150.93, 'portkembla', 0, 0, 'IDR033', 'batemans', 'bro', '', 100],
    ['Narrawallee / Mollymook north', 'South Coast', -35.313, 150.480, -35.31, 150.88, 'portkembla', 5, 10, 'IDR033', 'batemans', 'eb', '', 100],
    ['Lake Tabourie', 'South Coast', -35.435, 150.418, -35.44, 150.82, 'portkembla', 45, 70, 'IDR033', 'batemans', 'eb', '!Small, intermittently open lake.', 100],
    ['Bawley Point / Kioloa', 'South Coast', -35.510, 150.395, -35.51, 150.80, 'portkembla', 0, 0, 'IDR033', 'batemans', 'bro', '', 100],
    ['Durras / Durras Lake', 'South Coast', -35.634, 150.294, -35.63, 150.70, 'eden', 15, 15, 'IDR403', 'batemans', 'ebr', '!The lake is often closed to the sea.', 100],
    ['Malua Bay / Rosedale', 'South Coast', -35.792, 150.228, -35.79, 150.63, 'eden', 0, 0, 'IDR403', 'batemans', 'br', '', 90],
    ['Tomakin / Broulee', 'South Coast', -35.840, 150.194, -35.84, 150.60, 'eden', 5, 10, 'IDR403', 'batemans', 'ebr', '', 90],
    ['Tuross Head / Tuross Lake', 'South Coast', -36.060, 150.130, -36.06, 150.54, 'eden', 30, 45, 'IDR403', 'batemans', 'ebr', '', 90],
    ['Dalmeny / Mystery Bay', 'Far South Coast', -36.163, 150.132, -36.16, 150.54, 'eden', 0, 0, 'IDR403', 'batemans', 'br', '', 90],
    ['Wallaga Lake', 'Far South Coast', -36.365, 150.075, -36.37, 150.48, 'eden', 60, 90, 'IDR403', 'eden', 'e', '!Big, shallow lake — tide is a fraction of the coast.', null],
    ['Cuttagee / Murrah', 'Far South Coast', -36.494, 150.058, -36.49, 150.46, 'eden', 0, 0, 'IDR683', 'eden', 'br', '', 90],
    ['Bega River / Mogareeka', 'Far South Coast', -36.708, 149.987, -36.71, 150.40, 'eden', 20, 30, 'IDR683', 'eden', 'eb', '', 90],
    ['Wonboyn Lake', 'Far South Coast', -37.246, 149.940, -37.25, 150.35, 'eden', 60, 90, 'IDR683', 'eden', 'ebr', '!Lake is damped; the beach and rocks outside are open coast.', 100],
    ['Lake Hume', 'Inland', -36.100, 147.030, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Lake Mulwala / Murray (Corowa)', 'Inland', -35.990, 146.010, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Khancoban / Swampy Plain River', 'Inland', -36.220, 148.130, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Talbingo Dam / Tumut River', 'Inland', -35.580, 148.300, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Lake Lyell / Lake Wallace (Lithgow)', 'Inland', -33.520, 150.100, null, null, null, 0, 0, 'IDR713', null, 'f', '', null],
    ['Oberon Dam', 'Inland', -33.720, 149.870, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Ben Chifley Dam (Bathurst)', 'Inland', -33.520, 149.630, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Carcoar Dam', 'Inland', -33.630, 149.190, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Macquarie River (Dubbo)', 'Inland', -32.250, 148.600, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Lachlan River (Forbes)', 'Inland', -33.380, 148.010, null, null, null, 0, 0, 'IDR963', null, 'f', '', null],
    ['Lake Cargelligo', 'Inland', -33.290, 146.370, null, null, null, 0, 0, 'IDR943', null, 'f', '', null],
    ['Menindee Lakes', 'Inland', -32.390, 142.420, null, null, null, 0, 0, 'IDR943', null, 'f', '', null],
    ['Lake St Clair / Glennies Creek', 'Inland', -32.340, 151.290, null, null, null, 0, 0, 'IDR043', null, 'f', '', null],
    ['Lostock Dam', 'Inland', -32.330, 151.450, null, null, null, 0, 0, 'IDR043', null, 'f', '', null],
    ['Chaffey Dam (Tamworth)', 'Inland', -31.350, 151.140, null, null, null, 0, 0, 'IDR693', null, 'f', '', null],
    ['Split Rock Dam', 'Inland', -30.580, 150.700, null, null, null, 0, 0, 'IDR693', null, 'f', '', null],
    ['Pindari Dam', 'Inland', -29.400, 151.240, null, null, null, 0, 0, 'IDR533', null, 'f', '', null],
    ['Toonumbar Dam', 'Inland', -28.630, 152.740, null, null, null, 0, 0, 'IDR283', null, 'f', '', null],
    ['Clarence River (Copmanhurst)', 'Inland', -29.590, 152.780, null, null, null, 0, 0, 'IDR283', null, 'f', '', null],
    ['Namoi River (Gunnedah)', 'Inland', -30.980, 150.250, null, null, null, 0, 0, 'IDR693', null, 'f', '', null],
    ['Murrumbidgee (Gundagai)', 'Inland', -35.070, 148.100, null, null, null, 0, 0, 'IDR553', null, 'f', '', null],
    ['Edward River (Deniliquin)', 'Inland', -35.530, 144.960, null, null, null, 0, 0, 'IDR943', null, 'f', '', null],
    ['Yass River', 'Inland', -34.850, 148.900, null, null, null, 0, 0, 'IDR403', null, 'f', '', null],
    ['Googong Dam / Queanbeyan', 'Inland', -35.430, 149.260, null, null, null, 0, 0, 'IDR403', null, 'f', '', null],
    ['Lake Wyangan (Griffith)', 'Inland', -34.240, 146.030, null, null, null, 0, 0, 'IDR943', null, 'f', '', null],
    ['Darling River (Wilcannia)', 'Inland', -31.560, 143.380, null, null, null, 0, 0, 'IDR943', null, 'f', '', null]
  ];

  var KIND_NAME = { e: 'Estuary', b: 'Beach', r: 'Rock', o: 'Offshore', f: 'Freshwater' };

  var SPOTS = SPOT_ROWS.map(function (r, i) {
    return {
      id: i,
      name: r[0], region: r[1], lat: r[2], lon: r[3],
      sea: (r[4] === null ? null : { lat: r[4], lon: r[5] }),
      port: r[6], hwOff: r[7], lwOff: r[8],
      radar: r[9], district: r[10],
      kinds: r[11].split(''),
      note: (r[12] || '').replace(/^!/, ''),
      damped: /^!/.test(r[12] || ''),
      /* compass bearing the spot faces (where an onshore wind comes FROM);
         null for river, lake and inland water that no sea breeze reaches */
      faces: (r[13] === undefined ? null : r[13])
    };
  });

  /* ---------------- Species --------------------------------------------
     Legal limits verified against NSW DPIRD saltwater/freshwater bag and
     size limit tables, September 2026. season: 12 values Jan..Dec where
     0 = rarely about, 1 = around, 2 = peak run.                          */
  var SPECIES = [
    { n: 'Yellowfin bream', aka: 'bream, silver bream', cat: 'e', min: 25, max: null, bag: '10 combined with black bream & tarwhine (possession 20)', closed: null,
      season: [1,2,2,2,2,2,2,2,1,1,1,1], temp: [16,24], tide: 'Either — moving water', time: 'Dawn & dusk',
      run: 'Mature fish drop downstream and mass at river mouths, breakwalls and nearby beaches to spawn from late autumn through winter, then spread back through the estuaries in spring.',
      baits: ['Peeled prawn','Beach worm','Mullet strip','Half pilchard'], lures: ['3-5 g soft plastic grubs','Small hardbody cranks','Surface poppers','3.5 g blades'], where: 'Statewide' },
    { n: 'Dusky flathead', aka: 'dusky, lizard', cat: 'e', min: 36, max: 70, bag: '5 (possession 10) — 36-70 cm slot since 1 Aug 2026', closed: null,
      season: [2,2,2,2,1,1,1,1,2,2,2,2], temp: [18,26], tide: 'Run-out', time: 'Dawn & dusk',
      run: 'A resident ambush predator rather than a migrator — fish spread out of the deep winter holes onto the sand flats and drop-offs as water warms from September, with the big females most active over summer.',
      baits: ['Live poddy mullet','Whitebait','Pilchard','Live nipper'], lures: ['4-5 in paddle-tails','Prawn vibes','Shallow hardbodies','Blades'], where: 'Statewide, best in the big lakes and rivers' },
    { n: 'Sand whiting', aka: 'summer whiting', cat: 'e', min: 27, max: null, bag: '20', closed: null,
      season: [2,2,2,1,1,0,0,0,1,2,2,2], temp: [19,26], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Moves out of the estuaries to spawn in the surf zone and around river mouths through spring and summer; best on the flats in warm clear water on a big run-in tide.',
      baits: ['Live beach worm','Live nipper','Bloodworm','Pipi'], lures: ['Small surface poppers','2 in wrigglers','Small blades'], where: 'Statewide' },
    { n: 'Luderick', aka: 'blackfish, darkie', cat: 'e', min: 27, max: null, bag: '10 (possession 20)', closed: null,
      season: [1,1,2,2,2,2,2,2,1,1,0,1], temp: [14,21], tide: 'Run-in', time: 'All day',
      run: 'Schools leave the estuary weed beds and mass on ocean rocks and breakwalls to spawn through autumn and winter as the water cools and the swell builds, then filter back to the bridge pylons in spring.',
      baits: ['Green weed','Sea cabbage','Peeled prawn','Sandworm'], lures: [], where: 'Statewide' },
    { n: 'Mulloway', aka: 'jewfish, jewie, soapy', cat: 'e', min: 70, max: null, bag: '1 per person (2 per boat with 2+ aboard)', closed: null,
      season: [2,2,2,2,1,1,1,1,2,2,2,2], temp: [15,24], tide: 'Either — moving water', time: 'Night',
      run: 'Works between deep estuary holes and ocean beaches year round. The best sessions come on the four nights either side of new and full moon, on falling pressure ahead of a southerly, and one to three days after heavy rain pushes dirty water and baitfish out of the rivers.',
      baits: ['Live mullet','Live squid','Live yellowtail','Fresh tailor fillet'], lures: ['110-130 mm plastics','40-60 g micro jigs','Large minnows','Heavy vibes'], where: 'Statewide' },
    { n: 'Tarwhine', aka: 'silver bream', cat: 'e', min: 20, max: null, bag: '10 combined with bream (possession 20)', closed: null,
      season: [2,2,2,2,1,1,1,1,1,1,2,2], temp: [17,24], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Shadows yellowfin bream through the lower estuary and surf gutters, moving out to ocean beaches and headlands to spawn over the warmer months.',
      baits: ['Peeled prawn','Beach worm','Pipi','Squid strip'], lures: ['Small plastics','Small blades'], where: 'Statewide, more common north of Sydney' },
    { n: 'Estuary perch', aka: 'EP', cat: 'e', min: null, max: null, bag: '2 combined with Australian bass, only 1 over 35 cm in rivers', closed: '1 May – 31 Aug in rivers and estuaries (catch and release only)',
      season: [2,2,2,2,0,0,0,0,1,2,2,2], temp: [15,24], tide: 'Run-out', time: 'Night',
      run: 'Drops downstream into the salt reaches of coastal rivers to spawn over winter — the reason for the closure — then spreads back into the brackish snag and rock-bar country through spring.',
      baits: ['Live shrimp','Live prawn','Scrub worms'], lures: ['Small minnows','3 in plastics','Small spinnerbaits','Surface walkers'], where: 'Coastal rivers, south coast to the mid north coast' },
    { n: 'Blue swimmer crab', aka: 'blueys, sandy', cat: 'e', min: 6.5, max: null, bag: '10 (possession 20) — berried females must go back', closed: null,
      season: [2,2,2,2,1,0,0,0,1,1,2,2], temp: [20,27], tide: 'Run-in', time: 'Night',
      run: 'Moves up onto the shallow estuary flats and into the channels as water warms from October, peaking through summer and early autumn, then buries into deeper mud through the cold months.',
      baits: ['Mullet frames','Chicken frames','Fish heads'], lures: [], where: 'Statewide, best from Botany Bay north' },
    { n: 'Mud crab', aka: 'muddie, mangrove crab', cat: 'e', min: 8.5, max: null, bag: '5 — berried females must go back', closed: null,
      season: [2,2,2,2,1,0,0,0,0,1,2,2], temp: [22,30], tide: 'Run-in', time: 'Night',
      run: 'Warm-water crab that feeds hardest through summer and autumn in mangrove creeks and drains; post-rain runoff and water above about 22 °C gets them moving.',
      baits: ['Mullet frames','Chicken frames','Fish heads'], lures: [], where: 'North from about Port Stephens' },
    { n: 'Flounder', aka: 'largetooth flounder, sole', cat: 'e', min: 25, max: null, bag: '20 combined with sole', closed: null,
      season: [1,1,2,2,2,1,1,1,1,1,1,1], temp: [16,24], tide: 'Low slack', time: 'Night',
      run: 'Lies buried on estuary sand flats year round; numbers on the shallow flats build through autumn when calm clear nights make them easy to spot.',
      baits: ['Live nipper','Whitebait','Peeled prawn'], lures: ['Small plastics','Small blades'], where: 'Statewide estuaries' },
    { n: 'Eastern sea garfish', aka: 'gars, beakies', cat: 'e', min: null, max: null, bag: '20', closed: null,
      season: [1,1,2,2,2,2,2,1,1,1,1,1], temp: [15,22], tide: 'Run-in', time: 'All day',
      run: 'Holds over estuary weed beds and sheltered bays year round, thickening through the cooler months when a steady berley trail brings them up in calm clear water.',
      baits: ['Bread dough','Prawn slivers','Maggots','Silverfish'], lures: [], where: 'Statewide' },
    { n: 'Tailor', aka: 'chopper, bluefish', cat: 'b', min: 30, max: null, bag: '10 (possession 20)', closed: null,
      season: [1,1,2,2,2,2,2,2,2,1,1,1], temp: [17,23], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Big schools migrate north along the NSW coast through autumn and winter as the water cools, heading for the spawning grounds off southern Queensland. The leading edge of that run gives the best beach and headland fishing.',
      baits: ['Ganged pilchard','Whole garfish','Whole mullet'], lures: ['40-85 g slices','Surface poppers','Shallow minnows','Large plastics'], where: 'Statewide' },
    { n: 'Australian salmon', aka: 'sambo, black back', cat: 'b', min: null, max: null, bag: '5', closed: null,
      season: [1,1,1,2,2,2,2,2,2,2,1,1], temp: [14,20], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Cool-water schools push north up the coast as sea temperature drops from autumn — around Sydney from June, the Central Coast from July — peaking about September before withdrawing south again as summer warms the water.',
      baits: ['Pilchard on gangs','Beach worm','Whitebait'], lures: ['30-60 g slugs','Surface stickbaits','100-125 mm plastics'], where: 'Statewide, heaviest south of Newcastle' },
    { n: 'Rock blackfish', aka: 'black drummer, pig', cat: 'r', min: 30, max: null, bag: '10', closed: null,
      season: [1,1,2,2,2,2,2,2,1,1,1,1], temp: [15,22], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'A resident of the wash that feeds hardest through autumn and winter when heavy swell churns the ledges and strips weed and cunje off the rock.',
      baits: ['Cunjevoi','Peeled prawn','Bread','Sea cabbage'], lures: [], where: 'Statewide rocky headlands' },
    { n: 'Eastern blue groper', aka: 'NSW state fish', cat: 'r', min: null, max: null, bag: 'NO-TAKE — release only', closed: 'Line fishing prohibited statewide, extended three years from 1 Mar 2025',
      season: [1,1,1,1,1,1,1,1,1,1,1,1], temp: [16,23], tide: '—', time: 'All day',
      run: 'A highly site-attached rocky-reef wrasse, present year round on inshore headlands and kelp. It is NSW’s state fish and is currently no-take — release any you hook.',
      baits: [], lures: [], where: 'Statewide inshore reef', protected: true },
    { n: 'Silver trevally', aka: 'trevally, blurter', cat: 'r', min: 30, max: null, bag: '10 (possession 20)', closed: null,
      season: [1,1,1,2,2,2,2,2,2,1,1,1], temp: [15,22], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Schools thicken on inshore reefs, breakwalls and harbour wharves through the cooler months from about May to September, rising readily in a berley trail.',
      baits: ['Peeled prawn','Pilchard cubes','Squid strip','Beach worm'], lures: ['Small plastics','Blades & vibes','Micro jigs'], where: 'Statewide' },
    { n: 'Australian bonito', aka: 'bonito, horse mackerel', cat: 'r', min: null, max: null, bag: '10', closed: null,
      season: [2,2,2,2,2,1,0,0,1,1,1,2], temp: [18,24], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Warm-current schools arrive with the EAC from late spring and hold tight along headlands and inshore reefs through summer and autumn, chasing bait within casting range of the rocks.',
      baits: ['Live yellowtail','Pilchard on gangs','Garfish'], lures: ['20-40 g slugs','Trolled minnows','Stickbaits'], where: 'Statewide, best Sydney and south' },
    { n: 'Snapper', aka: 'reddie, squire, knobby', cat: 'o', min: 30, max: null, bag: '10', closed: null,
      season: [1,1,2,2,2,2,2,2,2,1,1,1], temp: [16,22], tide: 'Either — moving water', time: 'Dawn & dusk',
      run: 'Moves in from the deeper reef onto inshore reefs and headlands as the water cools from autumn and aggregates to spawn through winter and early spring, with the big reds pushing very shallow at first and last light.',
      baits: ['Fresh squid','Pilchard','Whole yellowtail','Octopus strip'], lures: ['5-7 in plastics','40-80 g micro jigs','Slow-pitch jigs'], where: 'Statewide' },
    { n: 'Yellowtail kingfish', aka: 'kingie, hoodlum, rat', cat: 'o', min: 65, max: null, bag: '5', closed: null,
      season: [2,2,2,2,1,1,1,1,2,2,2,2], temp: [18,24], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Numbers build from spring as the EAC pushes warm water south, holding on inshore reefs, FADs, bommies and moorings through summer and autumn, with a resident winter population on the deep grounds.',
      baits: ['Live squid','Live yellowtail','Live slimy mackerel','Live garfish'], lures: ['100-200 g knife jigs','Stickbaits','Large poppers'], where: 'Statewide, best Sydney, Port Stephens, south coast' },
    { n: 'Sand flathead', aka: 'bluespotted flathead', cat: 'o', min: 33, max: null, bag: '10 combined, all flathead except dusky (possession 20)', closed: null,
      season: [2,2,2,2,1,1,1,1,1,2,2,2], temp: [16,23], tide: 'Either — moving water', time: 'All day',
      run: 'Sits on offshore and bay sand patches in about 20-60 m year round; catches lift through the warmer months as fish spread into shallower sand.',
      baits: ['Squid strip','Pilchard','Whitebait'], lures: ['Plastics on 1/2-1 oz heads','Small jigs','Flasher rigs'], where: 'Statewide' },
    { n: 'Leatherjacket', aka: 'jacket, chinaman', cat: 'o', min: null, max: null, bag: '20 combined, all leatherjackets', closed: null,
      season: [1,1,1,2,2,2,2,2,2,1,1,1], temp: [15,23], tide: 'Either — moving water', time: 'All day',
      run: 'Swarms on inshore and offshore reef year round, with the thickest schools over the cooler months when they mob a berley trail.',
      baits: ['Squid strip','Peeled prawn','Pilchard cubes'], lures: ['Small jigs','Bait jigs'], where: 'Statewide' },
    { n: 'Morwong', aka: 'rubberlip, jackass morwong', cat: 'o', min: 30, max: null, bag: '10 (red morwong 5)', closed: null,
      season: [1,1,1,2,2,2,2,2,2,1,1,1], temp: [14,21], tide: 'Either — moving water', time: 'All day',
      run: 'Territorial deep-reef resident taken all year in 30-100 m; catches improve through the cooler months when the pelagics thin out and boats work the broken ground.',
      baits: ['Squid strip','Pilchard','Octopus'], lures: ['Plastics','Paternoster rigs'], where: 'Statewide' },
    { n: 'Pearl perch', aka: 'pearlie', cat: 'o', min: 30, max: null, bag: '5', closed: null,
      season: [1,1,2,2,2,2,2,2,1,1,1,1], temp: [18,24], tide: 'Either — moving water', time: 'Dawn & dusk',
      run: 'Deep-reef schooling fish of northern NSW holding on isolated hard reef in 50-120 m, most consistent through autumn and winter when the swell drops enough to reach the wide grounds.',
      baits: ['Fresh squid','Pilchard','Yellowtail fillet'], lures: ['Plastics','Slow-pitch jigs'], where: 'North from Port Stephens' },
    { n: 'Teraglin', aka: 'trag, trag jew', cat: 'o', min: 38, max: null, bag: '5', closed: null,
      season: [2,2,2,2,1,1,0,0,1,1,2,2], temp: [18,23], tide: 'Either — moving water', time: 'Night',
      run: 'Gathers over deep reef and gravel in 50-90 m and feeds hard after dark, most reliably from November to April when they lift well up in the water column at dusk.',
      baits: ['Fresh squid','Pilchard','Yellowtail strip'], lures: ['Plastics','Slow-pitch jigs'], where: 'Sydney to the mid north coast' },
    { n: 'Mackerel tuna', aka: 'kawakawa, false albacore', cat: 'o', min: null, max: null, bag: '20 (general limit — not separately listed)', closed: null,
      season: [2,2,2,2,2,1,0,0,0,1,1,2], temp: [21,27], tide: 'Either — moving water', time: 'Dawn & dusk',
      run: 'Warm-current schools follow the EAC down the coast from late spring, busting up on baitfish just off the headlands through summer and autumn before retreating north as it cools.',
      baits: ['Live yellowtail','Small live baits'], lures: ['20-40 g slugs','Small stickbaits','Trolled skirts'], where: 'North from Sydney' },
    { n: 'Spanish mackerel', aka: 'Spaniard', cat: 'o', min: 75, max: null, bag: '5 combined with spotted mackerel', closed: null,
      season: [2,2,2,2,1,0,0,0,0,1,1,2], temp: [22,28], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Follows the warm EAC south after spawning, arriving on northern NSW headlands once the water passes about 22 °C in late spring and holding through summer and autumn.',
      baits: ['Live slimy mackerel','Live pike','Whole garfish'], lures: ['Trolled bibless minnows','Large slugs','Skirted lures'], where: 'North from Coffs Harbour' },
    { n: 'Spotted mackerel', aka: 'spotty, doggie', cat: 'o', min: 60, max: null, bag: '5 combined with Spanish mackerel', closed: null,
      season: [2,2,2,2,1,0,0,0,0,0,1,2], temp: [22,28], tide: 'Run-in', time: 'Dawn & dusk',
      run: 'Fast schools track the warm current into northern NSW over summer, hunting small baitfish right on the surface off headlands and river mouths.',
      baits: ['Small live baits','Pilchard on gangs'], lures: ['20-40 g chrome slugs','Small trolled minnows'], where: 'North from Coffs Harbour' },
    { n: 'Cobia', aka: 'black kingfish, crab-eater', cat: 'o', min: null, max: null, bag: '5', closed: null,
      season: [2,2,2,2,1,0,0,0,0,1,2,2], temp: [22,28], tide: 'Either — moving water', time: 'All day',
      run: 'A warm-water nomad that arrives with the summer current, shadowing rays, buoys, FADs and bait schools over inshore reef before heading back north as it cools.',
      baits: ['Live yellowtail','Live pike','Whole squid'], lures: ['Large plastics','Big jigs','Surface poppers'], where: 'North from Sydney' },
    { n: 'Mahi mahi', aka: 'dolphinfish, dollie', cat: 'o', min: 60, max: null, bag: '10, only 1 over 110 cm', closed: null,
      season: [2,2,2,2,1,0,0,0,0,1,1,2], temp: [21,28], tide: '—', time: 'All day',
      run: 'Rides warm EAC eddies down the coast from about December, packing onto the DPIRD FADs, current lines and floating debris through summer and autumn until the water drops below about 21 °C.',
      baits: ['Pilchard','Live yellowtail','Fresh bonito strip'], lures: ['Small skirts','Stickbaits','Plastics','Poppers'], where: 'FADs from Merimbula to the Tweed' },
    { n: 'Marlin', aka: 'black, blue & striped marlin', cat: 'o', min: null, max: null, bag: '1 of each species per day', closed: null,
      season: [2,2,2,2,1,1,0,0,0,1,2,2], temp: [21,28], tide: '—', time: 'All day',
      run: 'Billfish follow the EAC south from November — small blacks work inshore off Port Stephens and the south coast through summer, blues hold on the shelf January to April, and stripes peak on the canyons from February into autumn.',
      baits: ['Live slimy mackerel','Live yellowtail','Swimming garfish'], lures: ['Skirted trolling lures','Large bibbed minnows'], where: 'Shelf and canyons statewide' },
    { n: 'Southern bluefin tuna', aka: 'SBT, barrel', cat: 'o', min: null, max: null, bag: '1', closed: null,
      season: [0,0,0,0,1,2,2,2,1,0,0,0], temp: [14,19], tide: '—', time: 'All day',
      run: 'Cold-water schools push up onto the NSW shelf and canyons from the south each winter as sea temperature falls, peaking off the south coast and Sydney between June and September.',
      baits: ['Pilchard cubes in a berley trail','Live slimy mackerel'], lures: ['Skirted lures','Deep divers','Metal jigs'], where: 'South coast to Sydney' },
    { n: 'Yellowfin tuna', aka: 'yellowfin, ’fin', cat: 'o', min: null, max: null, bag: '5 combined under 90 cm, 2 combined at 90 cm+', closed: null,
      season: [0,0,1,1,2,2,2,2,2,1,1,0], temp: [17,23], tide: '—', time: 'Dawn & dusk',
      run: 'Moves onto the NSW shelf and canyons as the water cools from autumn, with the biggest fish taken on a cube trail off the south coast and Sydney between May and October.',
      baits: ['Pilchard cubes','Live slimy mackerel'], lures: ['Skirted lures','Deep divers','Metal jigs'], where: 'Shelf statewide' },
    { n: 'Albacore', aka: 'albie, longfin tuna', cat: 'o', min: null, max: null, bag: '5 combined under 90 cm, 2 combined at 90 cm+', closed: null,
      season: [0,0,1,2,2,2,2,2,1,1,0,0], temp: [16,21], tide: '—', time: 'All day',
      run: 'Cool-water schools work the shelf break and canyons through autumn and winter, usually the first tuna to hit the spread once the water drops into the high teens.',
      baits: ['Pilchard cubes','Live slimy mackerel'], lures: ['Small skirts','Deep divers','Metal jigs'], where: 'Shelf statewide, best south' },
    { n: 'Eastern rock lobster', aka: 'crayfish, cray', cat: 'o', min: 10.4, max: 18, bag: '3 combined, all rock lobsters (up from 2 on 1 Aug 2026)', closed: null,
      season: [1,1,2,2,2,2,1,1,1,1,1,1], temp: [15,22], tide: 'Low slack', time: 'Night',
      run: 'Shelters in reef ledges and caves year round and comes out to feed at night; catches peak through autumn and winter when the swell is manageable and the water is clear.',
      baits: ['Mullet frames','Fish heads'], lures: [], where: 'Statewide rocky reef' },
    { n: 'School shark', aka: 'tope, greyboy', cat: 'o', min: 91, max: null, bag: '5 combined shark group, only 1 tiger/mako/hammerhead', closed: null,
      season: [1,1,2,2,2,2,2,2,1,1,1,1], temp: [13,19], tide: 'Either — moving water', time: 'Night',
      run: 'A bottom-dwelling shark of the deeper southern shelf, taken year round over soft bottom in 40-120 m, most consistently over the cooler months and after dark.',
      baits: ['Fresh squid','Salmon fillet','Tuna strip'], lures: [], where: 'South coast and Sydney' },
    { n: 'Australian bass', aka: 'bass', cat: 'f', min: null, max: null, bag: '2 combined with estuary perch, only 1 over 35 cm in rivers', closed: '1 May – 31 Aug in rivers and estuaries (catch and release only); dams open all year',
      season: [2,2,2,2,0,0,0,0,1,2,2,2], temp: [18,26], tide: '—', time: 'Dawn & dusk',
      run: 'Mature fish run downstream out of the freshwater reaches into the brackish lower estuary to spawn over winter — the reason for the closure — then migrate back up into the snag country from September as the water warms.',
      baits: ['Live shrimp','Scrub worms','Cicadas'], lures: ['Surface walkers','Small spinnerbaits','Shallow cranks','3 in plastics'], where: 'Coastal rivers and dams' },
    { n: 'Murray cod', aka: 'cod, goodoo', cat: 'f', min: 55, max: 75, bag: '2 (possession 4)', closed: '1 Sep – 30 Nov in inland waters (Copeton and Blowering dams open all year)',
      season: [2,2,2,1,1,1,1,1,0,0,0,2], temp: [18,24], tide: '—', time: 'Dawn & dusk',
      run: 'Territorial ambush predator that feeds hardest on warming water right after the 1 December opening; the opening weeks and summer low-light periods produce the most fish.',
      baits: ['Bardi grubs','Yabbies','Scrub worms'], lures: ['Spinnerbaits','Surface walkers','Swimbaits','Deep cranks'], where: 'Inland Murray-Darling rivers and dams' },
    { n: 'Golden perch', aka: 'yellowbelly, callop', cat: 'f', min: 30, max: null, bag: '5 (possession 10)', closed: null,
      season: [2,2,2,1,1,0,0,0,1,2,2,2], temp: [18,26], tide: '—', time: 'Dawn & dusk',
      run: 'Moves upstream on rising, warming water in spring — flow plus water above about 20 °C triggers both the spawning migration and heavy feeding — and shuts down almost completely in the coldest months.',
      baits: ['Yabbies','Scrub worms','Shrimp'], lures: ['Lipless cranks & vibes','Spinnerbaits','Blades'], where: 'Inland rivers and dams' },
    { n: 'Trout (rainbow & brown)', aka: 'rainbow trout, brown trout', cat: 'f', min: 25, max: null, bag: '5 general waters, 2 in artificial-only waters, 1 in spawning streams', closed: 'Streams closed from the Tuesday after the June long weekend to the Friday before the October long weekend; dams open all year',
      season: [1,1,2,2,2,1,0,0,0,2,2,2], temp: [8,17], tide: '—', time: 'Dawn & dusk',
      run: 'Browns and rainbows run up the Snowy Mountains rivers out of the lakes to spawn from about April to June, triggered by rain-driven rises — which is why the streams close. Spring and autumn give the best stream fishing while the dams keep going all winter.',
      baits: ['Scrub worms','Mudeyes','PowerBait where permitted'], lures: ['Bladed spinners','50-70 mm minnows','Soft plastic grubs','Wet & dry flies'], where: 'Snowy Mountains, New England, Central Tablelands' },
    { n: 'Carp', aka: 'European carp, mud marlin', cat: 'f', min: null, max: null, bag: 'No limit — declared pest', closed: null,
      season: [2,2,2,1,1,1,0,0,1,2,2,2], temp: [18,28], tide: '—', time: 'All day',
      run: 'Becomes highly active and spawns in the shallow margins and flooded backwaters through spring and summer; rising, warming, turbid water brings the biggest congregations.',
      baits: ['Corn kernels','Bread dough','Worms'], lures: ['Small plastics','Bread flies'], where: 'Inland and many coastal catchments', pest: true }
  ];

  /* ---------------- Statewide facts ------------------------------------- */
  var RULES = {
    asAt: 'September 2026',
    fee: { d3: 7, m1: 14, y1: 35, y3: 85,
      url: 'https://www.service.nsw.gov.au/services/recreational-fishing-licence',
      who: 'Everyone fishing in NSW waters, salt or fresh, by any method — including bait collecting and prawn netting. Carry the receipt.',
      exempt: ['Under 18', 'An adult helping someone under 18 with a single rod', 'Aboriginal people', 'Pensioner Concession Card (Centrelink or DVA)', 'Veteran Gold Card marked TPI or EDA', 'Private dams of 2 ha or less'] },
    lifejacket: {
      statewide: false, penalty: 100,
      areas: ['Ballina Shire','Central Coast','Kiama','Lake Macquarie','Northern Beaches','Port Stephens','Randwick','Richmond Valley','Sutherland Shire','Wollongong'],
      standard: 'Adults need AS 4758 level 50S or better; children under 12 need level 100 or better.',
      url: 'https://www.nsw.gov.au/environment-land-and-water/coasts-waterways-and-marine/rock-fishing-lifejacket-law' },
    general: [
      'A daily bag limit of 20 applies to anything not listed in the official tables.',
      'Possession limits count fish at home and in the freezer, not just what is on you.',
      'For bream, tarwhine, flathead, tailor, luderick, trevally, bass, estuary perch and blue swimmer crab the possession limit is twice the daily bag.',
      'All lobsters, crabs, bugs and crayfish carrying eggs must go back in the water.'
    ],
    noTake: ['Eastern blue groper (line fishing banned to about March 2028)','Wobbegong shark','Grey nurse shark','Black cod','Great white shark','Queensland groper','Seahorses, pipefish and seadragons','Trout cod, Macquarie perch, eastern freshwater cod'],
    links: {
      rules: 'https://www.dpird.nsw.gov.au/fishing/recreational/fishing-rules-and-regs/saltwater-bag-and-size-limits',
      freshRules: 'https://www.dpird.nsw.gov.au/fishing/recreational/fishing-rules-and-regs/freshwater-bag-and-size-limits',
      closures: 'https://www.dpird.nsw.gov.au/fishing/closures/general-closures',
      map: 'https://fishsmart-map.alantgeo.com.au/',
      report: 'tel:1800043536'
    }
  };

  global.FishData = {
    PORTS: PORTS, RADARS: RADARS, DISTRICTS: DISTRICTS,
    SPOTS: SPOTS, SPECIES: SPECIES, RULES: RULES, KIND_NAME: KIND_NAME
  };
})(typeof window !== 'undefined' ? window : globalThis);

if (typeof module !== 'undefined' && module.exports) module.exports = globalThis.FishData;
